name: elaina-testing

services:
  elaina:
    image: elaina:latest
    volumes:
      - type: volume
        source: devaina-data
        target: /run/data
    environment:
      ELAINA_DEBUG: $ELAINA_DEBUG
      DEVAINA_CLIENT_SECRET: $DEVAINA_CLIENT_SECRET
      DEVAINA_TOKEN: $DEVAINA_TOKEN

volumes:
  devaina-data:
    external: true