name: elaina

services:
  bot:
    image: elaina:latest
    volumes:
      - type: volume
        source: elaina-data
        target: /run/data
    secrets:
      - elaina-secret
      - elaina-token

volumes:
  elaina-data:
    external: true

secrets:
  elaina-secret:
    environment: ELAINA_CLIENT_SECRET
  elaina-token:
    environment: ELAINA_TOKEN